name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # https://tex.stackexchange.com/a/440271/2066
    # Try to create reproducible .pdfs
    env:
      SOURCE_DATE_EPOCH: "1"
      SOURCE_DATE_EPOCH_TEX_PRIMITIVES: "1"

    steps:
      - uses: actions/checkout@v2
      - name: Install Build Deps
        run: |
          sudo apt-get -o Acquire::Retries=30 update -q
          sudo apt-get -o Acquire::Retries=30 install -y --allow-unauthenticated \
            texlive \
            texlive-latex-extra \
            texlive-bibtex-extra \
            texlive-generic-extra \
            lmodern \
            wget \
            curl \
            sed \
            grep \
            aspell \
            aspell-en \
            #
      - run: make LATEX_EXTRA_FLAGS="-interaction=nonstopmode"
      - run: |
          mkdir -p deploy
          cp -t deploy/ coq-bug-minimizer.pdf
      - name: list
        run: |
          find .
          git status
      - name: Deploy pdfs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          SINGLE_COMMIT: false
        if: github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'schedule' )
