name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # https://tex.stackexchange.com/a/440271/2066
    # Try to create reproducible .pdfs

    env:
    - SOURCE_DATE_EPOCH: "1"
    - SOURCE_DATE_EPOCH_TEX_PRIMITIVES: "1"

    steps:
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Install Build Deps
        run: |
          sudo apt-get -o Acquire::Retries=30 update -q
          sudo apt-get -o Acquire::Retries=30 install -y --allow-unauthenticated \
            texlive \
            #
      - run: make LATEX_EXTRA_FLAGS="-interaction=nonstopmode"
      - run: make deploy
      - name: list
        run: |
          find .
          git status
      - name: Deploy pdfs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: deploy
          SINGLE_COMMIT: true
        if: github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'schedule' )
